#! /bin/bash

set -x
set -e

REPOSITORY=$1
DISTRIBUTION=$2

STABLE_DISTRIBUTION=testing
DISTRIBUTION_DIR=/var/www/public/$REPOSITORY/dists

for d in $STABLE_DISTRIBUTION ${REPOSITORY} ${REPOSITORY}-updates ${REPOSITORY}/updates ; do
 sudo rm -f $DISTRIBUTION_DIR/$d
 sudo ln -sf $DISTRIBUTION_DIR/$DISTRIBUTION $DISTRIBUTION_DIR/$d
done
