#! /bin/bash

usage() {
  echo "Usage: $0 [-s] [-w]  [-A architecture] [-C <component>] [-T (dsc|udeb|deb)] -r <repository> <fromDistribution> <toDistribution> <version>"
  echo "-s : simulate"
  echo "-w : wipe out <toDistribution> first"
  echo "-C <component>    : only act on component <component>"
  echo "-T (dsc,udeb,deb) : only act on source/udeb/deb packages"
  echo "-A <arch>         : only act on architecture <arch>"
  echo "please note that <version> needs to be a full x.y.z"
  exit 1
}

while getopts "A:T:C:shwr:d:m" opt ; do
  case "$opt" in
    s) simulate=1 && EXTRA_ARGS="$EXTRA_ARGS -s" ;;
    r) REPOSITORY=$OPTARG ;;
    C) COMPONENT="$OPTARG" && EXTRA_ARGS="$EXTRA_ARGS -C $COMPONENT" ;;
    A) ARCHITECTURE="$OPTARG" && EXTRA_ARGS="$EXTRA_ARGS -A $ARCHITECTURE" ;;
    T) TYPE="$OPTARG" && EXTRA_ARGS="$EXTRA_ARGS -T $TYPE" ;;
    w) WIPE_OUT_TARGET=1 ;;
    h) usage ;;
    \?) usage ;;
  esac
done
shift $(($OPTIND - 1))
if [ ! $# = 3 ] ; then
  usage
fi

FROM_DISTRIBUTION=$1
TO_DISTRIBUTION=$2
VERSION=$3

[ -z "$REPOSITORY" -o -z "$FROM_DISTRIBUTION" -o -z "$TO_DISTRIBUTION" ] && usage && exit 1

pkgtools=`dirname $0`
changelog_file=$(mktemp "promotion-$REPOSITORY-$FROM_DISTRIBUTION-to-$TO_DISTRIBUTION-$(date -Iminutes)-XXXXXXX.txt")
diffCommand="python3 $pkgtools/changelog.py.py --version $VERSION --tag-type promotion --create-tags"

. $pkgtools/release-constants.sh

##########
# MAIN
python $diffCommand >| $changelog_file

# wipe out target distribution first
[ -n "$WIPE_OUT_TARGET" ] && $pkgtools/remove-packages.sh $EXTRA_ARGS -r $REPOSITORY -d $TO_DISTRIBUTION

$pkgtools/copy-packages.sh $EXTRA_ARGS -r $REPOSITORY $FROM_DISTRIBUTION $TO_DISTRIBUTION

if [ -z "$simulate" ] ; then
  attachments="-a ${changelog_file}"
  mutt -F $MUTT_CONF_FILE $attachments -s "[Distro Promotion] $REPOSITORY: $FROM_DISTRIBUTION promoted to $TO_DISTRIBUTION" -- $RECIPIENT <<EOF
Effective $(date).

Attached is the changelog for this promotion, generated by running
the following command:

  $diffCommand

--ReleaseMaster ($USER@`hostname`)
EOF
fi

/bin/rm -f ${changelog_file}
