# CONSTANTS
REMOTE_USER="root"
REMOTE_SERVER="updates.untangle.com"
REPREPRO_BASE_DIR="/var/www/untangle"
REPREPRO_CONF_DIR="${REPREPRO_BASE_DIR}/conf"
REPREPRO_DISTRIBUTIONS_FILE="${REPREPRO_CONF_DIR}/distributions"
REPREPRO_BASE_COMMAND="reprepro -V -b ${REPREPRO_BASE_DIR}"
SSH_COMMAND="ssh ${REMOTE_USER}@${REMOTE_SERVER}"
REPREPRO_REMOTE_COMMAND="${SSH_COMMAND} ${REPREPRO_BASE_COMMAND}"
